### ISSUE TITLE
0.1.0rc11 v7 `runtime.pathStrict` disabled by default

### ISSUE THREAD

**Issue by KitCat962** [GrandpaScout/FiguraRewriteVSDocs#5] opened 2022-11-23 01:33 UTC
Seems a bit weird that `runtime.pathStrict` is disabled by default, when figura require paths must be strict.
`pathStrict` disabled:
![image](https://user-images.githubusercontent.com/94943674/203452972-0d979abc-3f2d-43bf-a304-1aca6afe59c5.png)
`pathStrict` enabled:
![image](https://user-images.githubusercontent.com/94943674/203452928-680c2939-5323-45de-9c0e-9bd33701b6dc.png)

**Comment by GrandpaScout** [comment] 2022-11-25 05:16
It's disabled because strict paths are incorrect when using the docs in the `avatars` folder. If used directly in an avatar folder then strict paths work as intended.

It is not something I can fix at the moment but that *may* change at some point.

**Comment by GrandpaScout** [comment] 2024-01-16 18:35
After all this time, this has finally been resolved in 15ca115 by just enforcing strict paths and not supporting using the docs with the `avatars` folder opened.

**Closed as completed by GrandpaScout** 2024-01-16 18:35 UTC
Labels: ☽ Lua Server, ★ Enhancement
